# Generated by Django 5.1.4 on 2024-12-07 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idpart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partner'),
        ),
    ]
