# Generated by Django 5.1.4 on 2024-12-07 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_idpart'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idpart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='partners.partner'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idrole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authentication.role'),
        ),
    ]
